name: Deploy (docs)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
        working-directory: ./
      - run: npm i
        working-directory: ./docs
      - run: npm run build
        working-directory: ./docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_book
